#!/usr/bin/env node
// One-off generator: read primeng-ref/icons/*/*.ts → emit dungeon-ui icon
// registry at projects/dungeon-ui/src/lib/icon/icons-data.ts.
//
// Strips clip-path machinery (the primeng icons clip to the full 14×14
// viewBox — a no-op — but the bindings need a unique runtime id we don't
// want to carry). Resulting body is plain SVG markup using currentColor.
//
// Delete this file after the registry exists. Re-run only if you want to
// re-sync from a newer primeng-ref.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PRIMENG_ICONS = path.resolve(ROOT, '../primeng-ref/packages/primeng/src/icons');
const OUT = path.resolve(ROOT, 'projects/dungeon-ui/src/lib/icon/icons-data.ts');

const SKIP = new Set(['baseicon']);

function kebab(folder) {
  // primeng uses selector `data-p-icon="angle-double-down"` — derive the same
  // canonical name from the source for accuracy.
  return folder;
}

function extractSelector(src) {
  const m = src.match(/data-p-icon="([^"]+)"/);
  return m ? m[1] : null;
}

function extractTemplate(src) {
  const m = src.match(/template:\s*`([\s\S]*?)`/);
  return m ? m[1].trim() : null;
}

function cleanBody(body) {
  let out = body;
  // <svg:foo …> → <foo …>  (namespaced only matters inside the @Component template).
  out = out.replace(/<svg:(\w+)/g, '<$1');
  out = out.replace(/<\/svg:(\w+)>/g, '</$1>');
  // Angular bindings: [attr.clip-path]="pathId" → drop (no clip-path needed)
  out = out.replace(/\s+\[attr\.clip-path\]="[^"]*"/g, '');
  out = out.replace(/\s+\[id\]="[^"]*"/g, '');
  // The defs/clipPath block exists only to anchor the binding above.
  // Strip the entire <defs>…</defs> block to keep the registry small.
  out = out.replace(/<defs>[\s\S]*?<\/defs>/g, '');
  // Collapse whitespace runs / blank lines.
  out = out.replace(/\s+/g, ' ').trim();
  // Final tidy: empty <g> wrappers left behind (search/etc).
  out = out.replace(/<g\s*>\s*([\s\S]*?)\s*<\/g>/g, '$1');
  return out;
}

const folders = fs.readdirSync(PRIMENG_ICONS, { withFileTypes: true })
  .filter(d => d.isDirectory() && !SKIP.has(d.name))
  .map(d => d.name)
  .sort();

const entries = [];
for (const folder of folders) {
  // Most icon folders match `<folder>/<folder>.ts`, but a few (e.g. filterfill)
  // ship the source under a different filename. Fall back to the first .ts that
  // declares a data-p-icon selector.
  let file = path.join(PRIMENG_ICONS, folder, `${folder}.ts`);
  if (!fs.existsSync(file)) {
    const alt = fs.readdirSync(path.join(PRIMENG_ICONS, folder))
      .filter(n => n.endsWith('.ts') && n !== 'public_api.ts' && n !== 'index.ts')
      .map(n => path.join(PRIMENG_ICONS, folder, n))
      .find(p => /data-p-icon=/.test(fs.readFileSync(p, 'utf8')));
    if (!alt) continue;
    file = alt;
  }
  const src = fs.readFileSync(file, 'utf8');
  const name = extractSelector(src) ?? kebab(folder);
  const body = extractTemplate(src);
  if (!body) continue;
  entries.push({ name, body: cleanBody(body) });
}

const names = entries.map(e => e.name);
const banner = `// AUTO-GENERATED by scripts/generate-icons.mjs from primeng-ref/icons.
// Re-run that script to refresh. Do not hand-edit individual entries.

`;
const nameUnion = `export type DgIconName =\n${names.map(n => `  | '${n}'`).join('\n')};\n`;
const list = `export const DG_ICON_NAMES: readonly DgIconName[] = [\n${names.map(n => `  '${n}',`).join('\n')}\n] as const;\n`;
const registry = `export const DG_ICONS: Record<DgIconName, string> = {\n${entries.map(e => `  '${e.name}': \`${e.body.replace(/`/g, '\\`')}\`,`).join('\n')}\n};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, banner + nameUnion + '\n' + list + '\n' + registry);
console.log(`Wrote ${entries.length} icons → ${OUT}`);
